version: "3"

services:
  mysql:
    container_name: mysql
    image: ${MYSQL_DOCKER_IMAGE}
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
  mongodb:
    container_name: mongodb
    image: ${MONGO_DOCKER_IMAGE}
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
  redis:
    container_name: redis
    image: ${REDIS_DOCKER_IMAGE}
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DATA_PATH}:/data

  # Hive
  # Ref: https://github.com/big-data-europe/docker-hive
  namenode:
    container_name: hadoop-namenode
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - ${HADOOP_NAMENODE_PATH}:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - config/hive/hadoop-hive.env
    ports:
      - "50070:50070"
      - "8020:8020"
  datanode:
    container_name: hadoop-datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - ${HADOOP_DATANODE_PATH}:/hadoop/dfs/data
    env_file:
      - ${HADOOP_HIVE_ENV_PATH}
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
  hive-server:
    container_name: hive-server
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ${HADOOP_HIVE_ENV_PATH}
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    container_name: hive-metastore
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ${HADOOP_HIVE_ENV_PATH}
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    container_name: hive-metastore-postgresql
    image: bde2020/hive-metastore-postgresql:2.3.0

  # Trino
  trino-coordinator:
    container_name: trino-coordinator
    image: ${TRINO_DOCKER_IMAGE}
    ports:
      - "8080:8080"
    environment:
      CATALOG_MANAGEMENT: "dynamic"
    volumes:
      - ${TRINO_COORDINATOR_CONFIG_PATH}:/etc/trino/config.properties
      - ${TRINO_CATALOG_PATH}/mysql.properties:/etc/trino/catalog/mysql.properties
      - ${TRINO_CATALOG_PATH}/mongodb.properties:/etc/trino/catalog/mongodb.properties
      - ${TRINO_CATALOG_PATH}/hive.properties:/etc/trino/catalog/hive.properties
  trino-worker-1:
    container_name: trino-worker-1
    image: ${TRINO_DOCKER_IMAGE}
    depends_on:
      - trino-coordinator
    ports:
      - "8081:8080"
    environment:
      CATALOG_MANAGEMENT: "dynamic"
    volumes:
      - ${TRINO_WORKER_CONFIG_PATH}:/etc/trino/config.properties
      - ${TRINO_CATALOG_PATH}/mysql.properties:/etc/trino/catalog/mysql.properties
      - ${TRINO_CATALOG_PATH}/mongodb.properties:/etc/trino/catalog/mongodb.properties
      - ${TRINO_CATALOG_PATH}/hive.properties:/etc/trino/catalog/hive.properties
  trino-worker-2:
    container_name: trino-worker-2
    image: ${TRINO_DOCKER_IMAGE}
    depends_on:
      - trino-coordinator
    ports:
      - "8082:8080"
    environment:
      CATALOG_MANAGEMENT: "dynamic"
    volumes:
      - ${TRINO_WORKER_CONFIG_PATH}:/etc/trino/config.properties
      - ${TRINO_CATALOG_PATH}/mysql.properties:/etc/trino/catalog/mysql.properties
      - ${TRINO_CATALOG_PATH}/mongodb.properties:/etc/trino/catalog/mongodb.properties
      - ${TRINO_CATALOG_PATH}/hive.properties:/etc/trino/catalog/hive.properties
  trino-worker-3:
    container_name: trino-worker-3
    image: ${TRINO_DOCKER_IMAGE}
    depends_on:
      - trino-coordinator
    ports:
      - "8083:8080"
    environment:
      CATALOG_MANAGEMENT: "dynamic"
    volumes:
      - ${TRINO_WORKER_CONFIG_PATH}:/etc/trino/config.properties
      - ${TRINO_CATALOG_PATH}/mysql.properties:/etc/trino/catalog/mysql.properties
      - ${TRINO_CATALOG_PATH}/mongodb.properties:/etc/trino/catalog/mongodb.properties
      - ${TRINO_CATALOG_PATH}/hive.properties:/etc/trino/catalog/hive.properties
