services:
  mysql:
    container_name: mysql
    image: ${MYSQL_DOCKER_IMAGE}
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
  mongodb:
    container_name: mongodb
    image: ${MONGO_DOCKER_IMAGE}
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
  redis:
    container_name: redis
    image: ${REDIS_DOCKER_IMAGE}
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data